import type { Metadata } from "next";
import {cn} from "@/lib/utils";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Quizzy',
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className,'antialiased min-h-screen ')}>
        <Providers>
         <Navbar />
         <main className="pt-16">
         {children}
         </main>
        </Providers>
      </body>
    </html>
  );
}
